apiVersion: v1
kind: Secret
metadata:
  name: fl-server-auth
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  ADMIN_PASSWORD_HASH: {{ .Values.admin.passwordHash | quote }}
  JWT_SECRET:          {{ .Values.admin.jwtSecret    | quote }}
